version: '3.1'
services:  
  codeblue:
    build:
      context: ./
    container_name: codeblue
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
      - ./node_modules
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway